
name = "beepi"
main = "src/beepi-worker.js"
compatibility_date = "2024-03-07"

[build]
command = "npm run build"

[observability.logs]
enabled = true

[secrets]
# These will be encrypted and stored securely:
# CLIENT_ID
# PRIVATE_KEY  
# BUSINESS_CERT
