name = "beepi"
main = "src/beepi-worker.js"
compatibility_date = "2024-03-07"

[build]
command = "npm run build"
upload.format = "service-worker"

[worker]
format = "esm"

[observability]
logs = false
