name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update wrangler.toml
        run: |
          if [ -f wrangler.toml ]; then
            sed -i 's/index.ts/index.js/g' wrangler.toml
          fi
        
      - name: Create test worker
        run: |
          echo 'export default { fetch() { return new Response("Hello World") } }' > index.js
          cat > wrangler-test.toml << EOF
          name = "beepiworker"
          main = "index.js"
          compatibility_date = "2023-11-15"
          EOF
        
      - name: Deploy test worker
        run: npx wrangler deploy --config wrangler-test.toml
          
      - name: Deploy main worker
        run: npx wrangler deploy